### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by pratiksha-ghanawat-minutus** [pratiksha-ghanawat-minutus/Vue_JS#1]
Create the Landing Page like "Welcome to Vue World !"

**Comment by pratiksha-ghanawat-minutus** [comment]
@sayali-minutus-21 Can you please create the Landing Page.

**Comment by sayali-minutus-21** [comment]
@pratiksha-minutus  Added the lading page ,can you please check once?

**Comment by sayali-tippe-minutus** [comment]
created landing page.
